#ifndef KERNEL_REGISTRY_H
#define KERNEL_REGISTRY_H

#include <string>

/**
 * @brief Auto-generated kernel registry for XML-driven OFX framework
 * 
 * This file is generated by generate_kernel_registry.py
 * DO NOT EDIT MANUALLY - changes will be overwritten
 */

// Kernel function type
typedef void (*KernelFunction)(
    void* stream, int width, int height,
    void* texture1, void* texture2, bool present1,
    void* texture3, bool present2,
    float* output,
    float param1, float param2, int param3, float param4
);

/**
 * @brief Get kernel function by effect name
 * @param effectName Name from XML effect definition
 * @return Function pointer or nullptr if not found
 */
KernelFunction getKernelFunction(const std::string& effectName);

/**
 * @brief Get number of registered effects
 * @return Number of effects in registry
 */
int getRegisteredEffectCount();

/**
 * @brief Get effect name by index
 * @param index Index in registry
 * @return Effect name or empty string if invalid index
 */
std::string getEffectName(int index);

#endif // KERNEL_REGISTRY_H
